api:
  accountRegion: 'americas'
  summonerRegion: 'na1'
  matchRegion: 'na1'

writeToFile: 
  enabled: true
  path: '../data/pre-cleaning-dataset.csv'
  encoding: 'utf8'
  hideIdentities: true
  removeTimelines: true
  pauseTime: 2500
  errorTime: 7500